# Generated by Django 4.2.23 on 2025-09-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('horsepower', models.FloatField()),
                ('torque', models.FloatField()),
                ('performance', models.FloatField()),
                ('total_speed', models.FloatField()),
                ('engine_cc', models.FloatField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('predicted_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
