# Generated by Django 4.2.23 on 2025-08-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoP', '0003_alter_car_photo1_path_alter_car_photo2_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo1_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo2_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo3_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo4_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo5_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo6_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo7_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo8_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
