# Generated by Django 4.2.23 on 2025-08-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoP', '0004_alter_car_photo1_path_alter_car_photo2_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo1_path',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo2_path',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo3_path',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo4_path',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo5_path',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo6_path',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo7_path',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo8_path',
        ),
        migrations.AddField(
            model_name='car',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo8',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
    ]
